{% set name = "binaryornot" %}
{% set version = "0.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 359501dfc9d40632edc9fac890e19542db1a287bbcfa58175b66658392018061

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - chardet >=3.0.2

# .pyc test fixtures are not included in the sdist
{% set deselect_tests = "--deselect=tests/test_check.py::TestProgrammingArtifacts::test_binary_pyc" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_check.py::TestProgrammingArtifacts::test_binary_empty_pyc" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_check.py::TestProgrammingArtifacts::test_binary_troublesome_pyc" %}

test:
  imports:
    - binaryornot
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - pytest tests/test_check.py {{ deselect_tests }}

about:
  home: https://github.com/audreyr/binaryornot
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Ultra-lightweight pure Python package to check if a file is binary or text.
  description: Ultra-lightweight pure Python package to check if a file is binary or text.
  dev_url: https://github.com/audreyr/binaryornot
  doc_url: https://github.com/audreyr/binaryornot

extra:
  recipe-maintainers:
    - bollwyvl