{% set name = "binaryornot" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc8d57cfa71d74ff8c28a7726734d53a851d02fad9e3a5581fb807f989f702f0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

# E FileNotFoundError: [Errno 2] No such file or directory: 'tests/isBinaryFile/this_is_not_a_bin.pyc'
# E FileNotFoundError: [Errno 2] No such file or directory: 'tests/files/.DS_Store'
{% set deselect_tests = "--deselect=tests/test_check.py::TestIsBinary::test_negative_binary" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_check.py::TestIsBinary::test_ds_store" %}
# E FileNotFoundError: [Errno 2] No such file or directory: 'uv'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_sdist.py::TestSdistContents::test_sdist_includes_pyc_fixtures" %}
# E PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\TASK_1~2\\AppData\\Local\\Temp\\tmpnjgs3nxd'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_check.py::TestErrorHandling::test_unreadable_file_raises" %}  # [win]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - pytest tests/test_check.py tests/test_encoding_coverage.py tests/test_sdist.py {{ deselect_tests }}


about:
  home: https://github.com/binaryornot/binaryornot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ultra-lightweight pure Python package to check if a file is binary or text.
  description: Ultra-lightweight pure Python package to check if a file is binary or text.
  dev_url: https://github.com/binaryornot/binaryornot
  doc_url: https://github.com/binaryornot/binaryornot/blob/main/README.md

extra:
  recipe-maintainers:
    - bollwyvl