travis:
  secure:
    BINSTAR_TOKEN: DV0bE+a94vaOO6HC6E9vkpIhrwcqQ5srdMeB8YkCkV59YzSbkYbxOvEd8Gy+7nXxv3O9luri4wwUVtMsSwt3IbzAG2hPWkOUTtM9RzVO2wfLG/xlo33oi56RsRjyCzHpnX/skSVyIIkfr7gLyBB65ieiJb3wVELkP4lUXA3h8JlKYYgX9TDtfY4eBIl/Hvf5+fshIEy0IFEYnPFo8+LYGvqJsaq/7iJjis6s9N6abgQUgUGjphIW+FuKG9J6dvWa9AfGTcYoI21Ywj0V8Vgb45RTxCGJH3MV6akzIXhJSJIbKJMEvO/47I70NNSp2TVqQ3fUOIWZA8bZLWqbRIzc3BPc4sbe61VyhmWLypl4NaU1BxqZSBNjm6ji8ot62uM7rPW1CBXph77CQH0RJ0DFemscnwutiELwcYzfyhjC0nwLD14S7ypRl1o49eAeISyXdU7qKrIkRW5KUvHbBy9fhRSh1iJSBLC90/5gMHtJAwN5rau73Xv5PxY7hKFz104gz7tyaZt6fuvZTvGnvWohwFFl40/BThNGafybregTZ9YwmleWRyqLefKpyAth6KWJIV1/6agJHkz21qVGHbkhRJrHY4DU3r5kPglxMK2EWFOK9e5Liv7obMjnr5BjNrNNTOEAGURurKZEOhJcd73FyIOdsp7kGv6v0tHl4Tgnujw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
