travis:
  secure:
    BINSTAR_TOKEN: M/HAW3kUDuu9y5cGmwTtEhcldn6yT5Z9ZJzw0og4V5ed900iyy9xnS0y2MKVQODXzImhoLh/KA5tTngAqGbYHVtA1okeeUMHwHTkNDR2z+OsbmTF5M06GZn6Pr875mXh/HRbhPYeOLUJ8xo8TiK10E65zArOTE6SBdPCqdsTmj8rknlotilb1eDOsc/Au0WemG0757hiGHWlE2labWv0Ag695vm6d7wiL9Qiw0MrZB6jBd7lq1Az/NEKmab3yVg8xP1rc4m/cNzggpAJXxdpvcKYOvX7EpIQUBOn7vuzGXnpZtM2MqRmBKp0WDt/C1O8MxiHGugphNpjxlWJIfbmlvkVxXkU56EMPLbfK1h0L/v20qtj5CduQrmhqBhfcT7RaQsotqWwAVjxWCAO1kBwAUdxP82bzc/o2qiwjhVm+9+Nm/pX8cHgMon6YHyAI3e41eheqbkqFIMRkCp+xrDfHarE0kpPuEuINDmbRqACDR0ytDN0oKtuAOrK9aGomQib/KpMCY4hK6dwP4VtzL4Cp2tXhGFK2Qac13VhGhPpTi1RilpwkMbG88P4WkWz41xsoWEdPcvL9kW5+d4HcVKvyPAONZ2LkddyQAqPHgxxtoYVBCPa6fvrHB3v02xiZ1AGcLGba8sKjuSDyR1HfZ5jrV+e1oaospFJInmxKMx7AxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
