travis:
  secure:
    BINSTAR_TOKEN: buHxA2PH+7CZMH0qQQpqO8bKzOGkNeZ+AzFdjao26voHkYqYByw/U0M+mhg051iIbdBJTxs4PpOcLO5AE1Izans1cHLj/QwP0uncqNtJ/0FPMeZco6Kwclo25OxzVDgeoQTpvsCknrcMphk8Gg9jj29aggdZr0AQj4z3lkjOXVLkA7hICjvoDk3JN+q8QOPNPP4dJUnK0iMJgCIdZPzfCsGtywX2asOSfSu8/+SAvidlgGW4+W667S/T8+zx1ilEIgd8zVPYT8m2COZEBaEwctN4udg/nVTrhYDRFdhMWKQTaewZchBR9x08Ne7zIjmJzbapczOw764lw2Nz73BY6Eqe9xfPX8whLXYvwXsRmoo+mxiR0bg+ebwtw6RJyq+JTeg9TqUcODmxGeRWRsnyaXCjX5IrDsXjq0g2OvvFbXofVjhVtTvPMdWFXR9Qa/NypraBFBieOPwC/778Db7Mw0lt+8eoNwivl6k5Jwj5ZdVotSvRXNpPHuJxIyhqnzXwVy07u9cf/E6fNLbb8Q4st/+FQNLMw5u7l8tgdP8NVc4ahFx21TgaUws3KOBXiUKF7KTeyfgsSFohAEk8KO6w3GPbM5o3uUUiY9jv/z8Qr6lILn5xlFZi9NHZwOuDxhb7s5RSuK8ICRyatnmCBvnKOTlRNPBNi7Fup9aKbUgBwmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
